name 'apache'
maintainer 'Nikhil Da Rocha'
maintainer_email 'niks77883@gmail.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'